package:
  name: nextflow
  version: "0.22.3"

build:
  number: 0

source:
  fn: nextflow
  url: https://github.com/nextflow-io/nextflow/releases/download/v0.22.3/nextflow
  md5: 3bca1ae17c7698e70ceeb6e0291c453a

requirements:
  run:
    - java-jdk >=7.0,<8.0

test:
  commands:
    - nextflow -v

about:
  home: "https://github.com/nextflow-io/nextflow"
  license: "GPL3"
  summary: "A DSL for data-driven computational pipelines http://nextflow.io"
