package:
  name: nextflow
  version: "0.22.4"

build:
  number: 0

source:
  fn: nextflow
  url: https://github.com/nextflow-io/nextflow/releases/download/v0.22.4/nextflow
  md5: fd544639e6caeb978966e867d6bf1ac6
  
requirements:
  run:
    - java-jdk >=7.0,<8.0

test:
  commands:
    - nextflow -v

about:
  home: "https://github.com/nextflow-io/nextflow"
  license: "GPL3"
  summary: "A DSL for data-driven computational pipelines http://nextflow.io"
